In [184]:
import numpy as np
import pandas as pd
import random
from ipywidgets import interact_manual

A = np.random.randint(0, 10, 64)
A = A.reshape(8,8)
guess1 = list(np.random.randint(0, 10, 4))
guess2 = list(np.random.randint(0, 10, 4))
guess3 = list(np.random.randint(0, 10, 4))
guess4 = list(np.random.randint(0, 10, 4))
ra1 = int(np.random.randint(0, 4, 1))
ra2 = int(np.random.randint(0, 4, 1))
#因用random選到在8*8矩陣中的4個連數機率太少有兩個從矩陣中抽出
s1 = list(A[ra1:ra1+4,ra1])
s2 = list(A[ra2,ra2:ra2+4])

savelist = [guess1,guess2,guess3,guess4,s1,s2]
savelist = random.sample(savelist, 6)#用ramdom.sample打亂順序

p = []
for j in range(len(A)):
    for i in range(len(A)):
        for k in savelist:
            if list(k) == list(A[0+i:4+i,j]):
                p.append(k)
            if list(k) == list(A[j,0+i:4+i]):
                p.append(k)

dic = {1:savelist[0], 2:savelist[1], 3:savelist[2], 4:savelist[3], 5:savelist[4], 6:savelist[5]}

def select(x):
    if x == '請選擇':
        print('請選擇')
    elif x == '':
        print('請選擇')
    elif dic[int(x)] in p:
        print('yes')
    else:
        print('no')

print(A)
print('請輸入號碼選擇有在矩陣行列內的連續數字，以下至少兩組數字會在矩陣內')
print(dic)
interact_manual(select, x='請選擇')

[[5 9 5 2 1 5 1 8]
 [1 9 1 2 5 5 2 7]
 [7 9 5 9 0 2 9 3]
 [2 4 2 6 5 0 2 2]
 [6 5 5 7 5 6 3 8]
 [8 2 4 7 7 6 4 2]
 [6 2 8 8 0 0 9 2]
 [2 5 7 4 2 6 9 9]]
請輸入號碼選擇有在矩陣行列內的連續數字，以下至少兩組數字會在矩陣內
{1: [3, 1, 7, 9], 2: [9, 9, 4, 5], 3: [1, 2, 8, 3], 4: [1, 3, 7, 5], 5: [5, 9, 0, 2], 6: [7, 9, 3, 8]}


interactive(children=(Text(value='請選擇', description='x'), Button(description='Run Interact', style=ButtonStyle…

<function __main__.select(x)>