In [1]:
import tensorflow as tf
import numpy as np
import os
from keras.backend import set_session
import pandas as pd

C:\Users\user\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
def create_session(gpu_id='0', pp_mem_frac=None):

    tf.reset_default_graph()
    os.environ["CUDA_VISIBLE_DEVICES"] = gpu_id # can multiple?
    with tf.device('/gpu:' + gpu_id):
        config = tf.ConfigProto()
        config.gpu_options.allow_growth = True
        if pp_mem_frac is not None:
            config.gpu_options.per_process_gpu_memory_fraction=pp_mem_frac
        session = tf.Session(config = config)
    return session

gpu_id = '0'
sess = create_session(gpu_id)
set_session(sess)

In [3]:
#定義layer
def add_layer(inputs, in_size, out_size, activation_function=None):
    Weights = tf.Variable(tf.random_normal([in_size, out_size]))
    biases = tf.Variable(tf.zeros([1, out_size]) + 0.1)
    Wx_plus_b = tf.matmul(inputs, Weights) + biases
    
    #選擇激活函數
    if activation_function is None:
        outputs = Wx_plus_b
    else:
        outputs = activation_function(Wx_plus_b)
    return outputs

In [4]:
x_data = pd.read_csv("traindata.csv")
y_data = pd.read_csv("label.csv")

In [5]:
#將Nan轉為0
x_data = x_data.fillna(0)
y_data = y_data.fillna(0)

In [7]:
#將不必要的欄位切掉(每次讀只能跑一次)
x_data=x_data.iloc[:,1:]
y_data=y_data.iloc[:,1:]

In [8]:
x_data = x_data.iloc[0:10000]
y_data = y_data.iloc[0:10000]

0          1         2          3         4          5         6  \
0    -8.639847  41.159826 -8.640351  41.159871 -8.642196  41.160114 -8.644455   
1    -8.612964  41.140359 -8.613378  41.140350 -8.614215  41.140278 -8.614773   
2    -8.574678  41.151951 -8.574705  41.151942 -8.574696  41.151933 -8.574660   
3    -8.645994  41.180490 -8.645949  41.180517 -8.646048  41.180049 -8.646804   
4    -8.615502  41.140674 -8.614854  41.140926 -8.613351  41.141520 -8.609976   
5    -8.579520  41.145948 -8.580942  41.145039 -8.582706  41.145021 -8.584092   
6    -8.617563  41.146182 -8.617527  41.145849 -8.616978  41.144832 -8.615754   
7    -8.611794  41.140557 -8.611785  41.140575 -8.612001  41.140566 -8.612622   
8    -8.615907  41.140557 -8.614449  41.141088 -8.613522  41.141430 -8.609904   
9    -8.619894  41.148009 -8.620164  41.147730 -8.620650  41.148513 -8.620920   
10   -8.562420  41.168403 -8.562429  41.168358 -8.562348  41.167953 -8.564571   
11   -8.618868  41.155101 -8.617500  41.154912 -8.615079  41.154525 -8.613468   
12   -8.608716  41.153499 -8.607627  41.153481 -8.606502  41.153472 -8.606493   
13   -8.612208  41.140530 -8.612235  41.140521 -8.614035  41.140323 -8.614809   
14   -8.585145  41.164857 -8.584146  41.164704 -8.583147  41.164758 -8.627931   
15   -8.584263  41.163156 -8.584695  41.163003 -8.585595  41.162652 -8.585487   
16   -8.666757  41.174055 -8.666784  41.174064 -8.666649  41.174073 -8.666325   
17   -8.599239  41.149188 -8.598681  41.149296 -8.597943  41.150583 -8.596962   
18   -8.643807  41.168979 -8.642529  41.170113 -8.642133  41.171202 -8.643240   
19   -8.609706  41.151303 -8.609562  41.151474 -8.610021  41.152509 -8.609769   
20   -8.660646  41.168574 -8.661087  41.167926 -8.661231  41.166576 -8.660637   
21   -8.612955  41.140377 -8.612991  41.140359 -8.613090  41.140368 -8.613297   
22   -8.604180  41.160969 -8.603874  41.161500 -8.603910  41.161527 -8.603919   
23   -8.665686  41.170626 -8.665677  41.170653 -8.664786  41.171319 -8.663238   
24   -8.632737  41.168295 -8.632800  41.168250 -8.632845  41.168205 -8.632836   
25   -8.648226  41.148333 -8.648514  41.148297 -8.648784  41.148153 -8.650827   
26   -8.638227  41.159592 -8.637543  41.159250 -8.635158  41.158881 -8.633196   
27   -8.613243  41.154444 -8.612811  41.153733 -8.611965  41.154642 -8.611920   
28   -8.611065  41.149431 -8.611209  41.149368 -8.611236  41.148243 -8.611794   
29   -8.611101  41.162850 -8.611110  41.162976 -8.611020  41.164443 -8.609157   
...        ...        ...       ...        ...       ...        ...       ...   
9970 -8.609697  41.153661 -8.609859  41.153634 -8.609931  41.153607 -8.609985   
9971 -8.591256  41.162760 -8.591031  41.162589 -8.591202  41.162292 -8.591832   
9972 -8.638452  41.170959 -8.638110  41.170581 -8.637381  41.170185 -8.637129   
9973 -8.649396  41.154318 -8.649756  41.154336 -8.649972  41.154399 -8.650089   
9974 -8.574849  41.142843 -8.574714  41.142798 -8.575326  41.143212 -8.575632   
9975 -8.647146  41.160924 -8.647506  41.160987 -8.648802  41.161212 -8.649846   
9976 -8.574696  41.142681 -8.574687  41.142717 -8.574696  41.142717 -8.574642   
9977 -8.649585  41.167242 -8.649783  41.166486 -8.648190  41.166063 -8.647857   
9978 -8.625933  41.157297 -8.625924  41.157351 -8.625141  41.157207 -8.625987   
9979 -8.648271  41.170437 -8.648001  41.170599 -8.646867  41.169825 -8.645958   
9980 -8.568369  41.153454 -8.568324  41.153454 -8.568306  41.153445 -8.568297   
9981 -8.610948  41.145750 -8.610885  41.145759 -8.610777  41.145903 -8.610372   
9982 -8.639973  41.159799 -8.639982  41.159799 -8.639946  41.159727 -8.641233   
9983 -8.610705  41.141223 -8.610714  41.141196 -8.613684  41.141448 -8.614431   
9984 -8.639910  41.159763 -8.640531  41.159808 -8.640504  41.159808 -8.640504   
9985 -8.607510  41.145498 -8.607483  41.145462 -8.607393  41.145633 -8.607087   
9986 -8.606520  41.144778 -8.606619  41.144823 -8.607006  41.145021 -8.607816   
9987 -8.600139  41.182704 -8.600274  41.1827

In [9]:
len(x_data)

10000

In [10]:
len(x_data.iloc[0])

5030

In [11]:
xs = tf.placeholder(tf.float32, [None, 5030])
ys = tf.placeholder(tf.float32, [None, 2])

In [12]:
l1 = add_layer(xs, 5030, 2000, activation_function = tf.nn.tanh)
l2 = add_layer(l1, 2000, 200, activation_function = tf.nn.tanh)
l3 = add_layer(l2, 200, 20, activation_function = tf.nn.tanh)
outputlayer = add_layer(l3, 20, 2, activation_function = None)
loss = tf.reduce_mean(tf.reduce_sum(tf.square(ys - outputlayer)))
# adam是改良的gd ,learning rate會越來越小
train_step = tf.train.AdamOptimizer(0.03).minimize(loss)

In [13]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
batch = 40

In [14]:
for i in range(250):
    print(i)
    sess.run(train_step, feed_dict={xs: x_data.iloc[(batch*i):(batch*(i+1)),:], ys: y_data.iloc[(batch*i):(batch*(i+1)),:]})
    print(sess.run(loss, feed_dict={xs: x_data.iloc[(batch*i):(batch*(i+1)),:], ys: y_data.iloc[(batch*i):(batch*(i+1)),:]}))
    print(sess.run(outputlayer, feed_dict={xs: x_data.iloc[batch*i:batch*(i+1),:], ys: y_data.iloc[batch*i:batch*(i+1),:]}))

0
47436.71
[[-4.69447     7.93619   ]
 [ 1.0678941   3.543085  ]
 [ 0.9246686   4.8427434 ]
 [-3.876284    6.6509795 ]
 [-4.9251533   9.481544  ]
 [ 2.6538713   8.133714  ]
 [-1.4048077   4.641427  ]
 [ 0.35582334  8.250739  ]
 [-3.3447018   9.243506  ]
 [-5.0349174  11.070991  ]
 [ 2.0640368  12.047528  ]
 [-0.92452806  8.812984  ]
 [-1.4034094   4.6406674 ]
 [-3.211125    7.45758   ]
 [-3.071379    5.0672736 ]
 [ 1.793808    3.734295  ]
 [-4.5579796   7.937522  ]
 [-4.630379    9.472911  ]
 [ 1.107694    6.439211  ]
 [-0.37829822  3.5078192 ]
 [ 0.93160516  4.877263  ]
 [ 0.6921182   7.263302  ]
 [-7.0013156   6.91576   ]
 [-4.9384675   9.4816675 ]
 [ 0.38533336  3.9046822 ]
 [-4.2346683   8.79065   ]
 [-3.063308    6.871259  ]
 [-5.563773    8.100234  ]
 [ 2.2695677  10.302742  ]
 [-5.564699    8.09775   ]
 [ 2.194151   10.30976   ]
 [ 0.28130692  8.520196  ]
 [ 2.6593497   8.150256  ]
 [-4.6686845   9.43985   ]
 [ 1.1714467   6.033263  ]
 [-4.930308    9.481975  ]
 [-5.563601    8.

[[-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]
 [-8.147538 25.279547]]
19
9350.13
[[-8.542124  25.839043 ]
 [-6.6124163 12.115707 ]
 [-8.542124  25.83

[[-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]
 [-9.774728 34.99786 ]]
39
1381.0857
[[-9.61357  35.377647]
 [-9.61357  35.377647]
 [-9.61357  35.37764

35.57672
[[-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]
 [-8.389944 40.24252 ]]
59
26.209595
[[-8.428897 40.3845  ]
 [-8.428897 40.3845  ]
 [-8.428897

2481.729
[[ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [  7.598852  -10.491483 ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [ -8.93452    41.58855  ]
 [  7.5989394 -10.4

2.178402
[[-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]
 [-8.603034 41.388714]]
99
1631.5312
[[-8.600834 41.371647]
 [-8.600834 41.371647]
 [13.223915

0.14931148
[[-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.66253   41.148663 ]
 [-8.6622305 4

1275.4481
[[-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [16.530628 -5.590555]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [16.530628 -5.590555]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]
 [-8.657589 41.1269  ]]
139
0.16375358
[[-8.658286 41.127705]
 [-8.658286 41.127705]
 [-8.658

566.28986
[[-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [ 1.1218356e+00 -5.8140755e-03]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]
 [-8.6316833e+00  4.1152451e+01]


495.33936
[[-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [ 1.5255086e+00  1.6605258e-02]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [ 1.9623671e+01 -5.4286513e+00]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]
 [-8.6649971e+00  4.1157993e+01]


1206.3486
[[-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [21.827068  -5.2951984]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [21.827068  -5.2951984]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [-8.694109  41.1455   ]
 [21.827068  -5.2951984]
 [-8.694109  41.1455   ]
 [-8.694109  41

306.6808
[[-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [24.40369   -5.1277876]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.145554 ]
 [-8.626345  41.

[[-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [25.675514  -5.0397177]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]
 [-8.661003  41.156075 ]]

In [15]:
#用test.csv做預測後上傳檔案至kaggle
dft = pd.read_csv("test.csv")
dft = dft["POLYLINE"].str.replace("[","")
dft = dft.str.replace("],",",")
dft = dft.str.replace("]","")
dft = dft.str.split(",",-1,True)
dft.fillna(value=0, inplace=True)
dft = dft.astype(float)

In [16]:
dft

0          1         2          3         4          5         6     \
0   -8.585676  41.148522 -8.585712  41.148639 -8.585685  41.148855 -8.585730   
1   -8.610876  41.145570 -8.610858  41.145579 -8.610903  41.145768 -8.610444   
2   -8.585739  41.148558 -8.585730  41.148828 -8.585721  41.148972 -8.586288   
3   -8.613963  41.141169 -8.614125  41.141124 -8.615088  41.140926 -8.615277   
4   -8.619903  41.148036 -8.619894  41.148036  0.000000   0.000000  0.000000   
5   -8.630613  41.178249 -8.630613  41.178249 -8.630739  41.178231 -8.631513   
6   -8.585622  41.148918 -8.585640  41.148900 -8.585919  41.148945 -8.586369   
7   -8.582922  41.181057 -8.582004  41.181813 -8.581077  41.182965 -8.580114   
8   -8.606529  41.144670 -8.606673  41.144724 -8.606799  41.144706 -8.606790   
9   -8.585658  41.148576 -8.585703  41.148603 -8.585730  41.148603 -8.585739   
10  -8.591229  41.162706 -8.591229  41.162715 -8.591220  41.162715 -8.591004   
11  -8.585694  41.148603 -8.585757  41.148684 -8.585712  41.148882 -8.585757   
12  -8.580105  41.159394 -8.580231  41.159358 -8.581518  41.159349 -8.582517   
13  -8.665353  41.186160 -8.666892  41.188311 -8.667045  41.190705 -8.665812   
14  -8.649423  41.154354 -8.650197  41.154138 -8.650323  41.153832 -8.649045   
15  -8.618373  41.136003 -8.618382  41.135877 -8.618445  41.135022 -8.618445   
16  -8.627094  41.166936 -8.627049  41.166900 -8.626644  41.166900 -8.626626   
17  -8.607861  41.146236 -8.607915  41.146236 -8.607924  41.146236 -8.607924   
18  -8.585667  41.148567 -8.585694  41.148639 -8.585712  41.148747 -8.585775   
19  -8.667414  41.161671 -8.667423  41.161662 -8.667414  41.161671 -8.667405   
20  -8.585712  41.148540 -8.585703  41.148549 -8.585712  41.148558 -8.585721   
21  -8.612757  41.137722 -8.612658  41.137785 -8.612631  41.137812 -8.612460   
22  -8.625816  41.151294 -8.625942  41.151330 -8.626113  41.151294 -8.626284   
23  -8.585658  41.148486 -8.585658  41.148486 -8.585658  41.148486 -8.585658   
24  -8.630667  41.154867 -8.630928  41.154660 -8.632386  41.153166 -8.633241   
25  -8.602830  41.179644 -8.603163  41.179716 -8.604648  41.180139 -8.604990   
26  -8.592120  41.160735 -8.591499  41.161689 -8.592093  41.161581 -8.593029   
27  -8.585685  41.148900 -8.586018  41.148990 -8.587017  41.149098  0.000000   
28  -8.628777  41.160978 -8.628741  41.160969 -8.628750  41.160960 -8.628777   
29  -8.585730  41.148513 -8.585748  41.148846 -8.586198  41.149044 -8.586234   
..        ...        ...       ...        ...       ...        ...       ...   
290 -8.627697  41.175432 -8.627463  41.174766 -8.626617  41.173038 -8.625924   
291 -8.661942  41.183703 -8.661942  41.183694 -8.661933  41.183649 -8.663220   
292 -8.573454  41.147199 -8.573499  41.147262 -8.573517  41.147289 -8.573526   
293 -8.606403  41.144454 -8.606430  41.144544 -8.606430  41.144562 -8.606430   
294 -8.610264  41.140845 -8.610066  41.140809 -8.610057  41.140845 -8.610048   
295 -8.612136  41.172849 -8.612667  41.172804 -8.612685  41.172084  0.000000   
296 -8.641251  41.165658 -8.641260  41.165712 -8.641269  41.165721 -8.641863   
297 -8.613891  41.141286 -8.614350  41.141115 -8.615511  41.140701 -8.616780   
298 -8.620461  41.156514 -8.620506  41.156469 -8.620641  41.156460 -8.620650   
299 -8.617581  41.146110 -8.617590  41.146092 -8.617518  41.145678 -8.617212   
300 -8.588457  41.148558 -8.588844  41.147199 -8.587206  41.147298 -8.585613   
301 -8.589096  41.155506 -8.589105  41.155515 -8.589114  41.155515 -8.589123   
302 -8.668575  41.157891 -8.668575  41.157909 -8.667999  41.158161 -8.666046   
303 -8.607456  41.148720 -8.607060  41.148621 -8.606772  41.148513 -8.606475   
304 -8.617113  41.160042 -8.617122  41.160069 -8.617122  41.160114 -8.616726   
305 -8.628984  41.165874 -8.629074  41.165874 -8.630334  41.165343 -8.631657   
306 -8.619723  41.161905 -8.619768  41.161959 -8.619813  41.161995 -8.619822   
307 -8.623566  41.144310 -8.623593  41.144328 -8.624790  41.144706 -8.627292   
308 -8.61

In [17]:
dfnew = pd.DataFrame(np.zeros((len(dft),(len(x_data.iloc[0]) - len(dft.iloc[0]))))) 
dft = pd.concat([dft, dfnew],axis = 1)

In [18]:
output = sess.run(outputlayer, feed_dict = {xs : dft})

In [19]:
#output.csv需要打開更改row跟col的名稱才能上傳kaggle
output  = pd.DataFrame(output)
output.to_csv("outputmidtest.csv")