# ECML/PKDD 15: Taxi Trajectory Prediction (I)

此為在Kaggle比賽中找到的一個以前的比賽，是用計程車前面經過的地點(經緯度)來預測他的目的地(經緯度)

我覺得此題目重要並有趣的原因是在於，若預測準確，可以提早知道乘客下車的地點，並能通知司機知道他下一個能服務的乘客距離此地點近不近，他可以大大提升計程車公司的效率。

此比賽在kaggle上的評分標準是用Mean Haversine Distance，它根據緯度和經度測量球體上兩點之間的距離(這樣才不會因為地球是球體而有偏誤)，而我目前用神經網路得到的分數是3.54468，雖然名次不是很漂亮(名次在總體的2/3左右)，但我覺得是模型的限制，若是之後學習到更適合處理time series資料的模型，相信可以得到更好的分數

p.s.為了想練習tensorflow此報告我使用tensorflow實做

![分數](mid2000_200_20_354468.PNG)

In [1]:
import tensorflow as tf
import numpy as np
import os
import pandas as pd

In [2]:
#定義layer
def add_layer(inputs, in_size, out_size, activation_function=None):
    Weights = tf.Variable(tf.random_normal([in_size, out_size]))
    biases = tf.Variable(tf.zeros([1, out_size]) + 0.1)
    Wx_plus_b = tf.matmul(inputs, Weights) + biases
    
    #選擇激活函數
    if activation_function is None:
        outputs = Wx_plus_b
    else:
        outputs = activation_function(Wx_plus_b)
    return outputs

In [5]:
x_data = pd.read_csv("traindata.csv")
y_data = pd.read_csv("label.csv")

In [6]:
#將Nan轉為0
x_data = x_data.fillna(0)
y_data = y_data.fillna(0)

In [7]:
#將不必要的欄位切掉(每次讀只能跑一次)
x_data=x_data.iloc[:,1:]
y_data=y_data.iloc[:,1:]

In [8]:
x_data = x_data.iloc[0:10000]
y_data = y_data.iloc[0:10000]

In [9]:
len(x_data)

10000

In [10]:
len(x_data.iloc[0])

5030

In [11]:
xs = tf.placeholder(tf.float32, [None, 5030])
ys = tf.placeholder(tf.float32, [None, 2])

In [12]:
l1 = add_layer(xs, 5030, 2000, activation_function = tf.nn.tanh)
l2 = add_layer(l1, 2000, 200, activation_function = tf.nn.tanh)
l3 = add_layer(l2, 200, 20, activation_function = tf.nn.tanh)
outputlayer = add_layer(l3, 20, 2, activation_function = None)
loss = tf.reduce_mean(tf.reduce_sum(tf.square(ys - outputlayer)))
# adam是改良的gd ,learning rate會越來越小
train_step = tf.train.AdamOptimizer(0.03).minimize(loss)

In [13]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
batch = 40

In [14]:
for i in range(250):
    print(i)
    sess.run(train_step, feed_dict={xs: x_data.iloc[(batch*i):(batch*(i+1)),:], ys: y_data.iloc[(batch*i):(batch*(i+1)),:]})
    print(sess.run(loss, feed_dict={xs: x_data.iloc[(batch*i):(batch*(i+1)),:], ys: y_data.iloc[(batch*i):(batch*(i+1)),:]}))
    print(sess.run(outputlayer, feed_dict={xs: x_data.iloc[batch*i:batch*(i+1),:], ys: y_data.iloc[batch*i:batch*(i+1),:]}))

0
38169.695
[[-6.63271964e-01  1.28269320e+01]
 [ 3.02976823e+00  1.50880728e+01]
 [ 5.15637350e+00  1.56364985e+01]
 [ 7.69720030e+00  1.12390871e+01]
 [ 4.98141587e-01  1.13589020e+01]
 [-3.17311454e+00  1.03342533e+01]
 [ 1.73270464e+00  1.15152426e+01]
 [-1.10145414e+00  1.37578621e+01]
 [-5.94117582e-01  1.28366785e+01]
 [ 2.13565803e+00  1.38602095e+01]
 [ 8.54679883e-01  1.52788811e+01]
 [ 2.39189315e+00  1.19525490e+01]
 [ 1.67278898e+00  1.15004435e+01]
 [-7.26069093e-01  9.76208210e+00]
 [ 1.58105642e-02  1.59996662e+01]
 [ 3.42044282e+00  1.50763407e+01]
 [-6.15553081e-01  1.28357954e+01]
 [ 5.41538715e+00  1.38014650e+01]
 [ 6.29165173e+00  1.00692282e+01]
 [ 3.93590617e+00  1.17471476e+01]
 [ 5.15759039e+00  1.56374998e+01]
 [ 4.23564911e+00  7.94264317e+00]
 [-8.97597730e-01  1.31243925e+01]
 [ 2.59899473e+00  1.10683622e+01]
 [ 6.08633471e+00  1.16355391e+01]
 [ 1.31894946e+00  1.46866322e+01]
 [ 7.75789499e+00  1.12361746e+01]
 [ 5.15103197e+00  1.38122015e+01]
 [ 1.110

20053.51
[[-9.30474   19.097576 ]
 [-6.0072904 19.391012 ]
 [-6.0213985 19.389757 ]
 [-9.302525  19.09777  ]
 [-6.007252  19.391016 ]
 [-6.00746   19.390997 ]
 [-6.007252  19.391016 ]
 [-8.182537  19.19744  ]
 [-9.304734  19.097574 ]
 [-6.007252  19.391016 ]
 [-6.007251  19.391016 ]
 [-6.2068257 19.373255 ]
 [-6.007252  19.391016 ]
 [-9.304755  19.097574 ]
 [-6.007252  19.391016 ]
 [-9.274457  19.10027  ]
 [-6.0072546 19.391016 ]
 [-9.285285  19.102198 ]
 [-6.206818  19.373257 ]
 [-6.0102654 19.390749 ]
 [-5.5186157 19.996836 ]
 [-9.30468   19.097591 ]
 [-9.301822  19.097834 ]
 [-7.2086883 19.284101 ]
 [-9.303887  19.09765  ]
 [-9.1914835 19.107653 ]
 [ 6.654299   5.521814 ]
 [-6.007252  19.391016 ]
 [-6.0082917 19.390924 ]
 [-9.061845  19.119188 ]
 [-6.007252  19.391016 ]
 [-6.0077767 19.39097  ]
 [-6.0073957 19.391005 ]
 [-6.0085216 19.390903 ]
 [-9.015544  19.123308 ]
 [-6.007252  19.391016 ]
 [-6.032545  19.388765 ]
 [-9.280626  19.09972  ]
 [-6.2069488 19.373245 ]
 [-6.007252  19.

11611.372
[[-5.159261  24.485256 ]
 [-5.15926   24.485256 ]
 [-5.1592607 24.485256 ]
 [-5.15926   24.485256 ]
 [-5.159262  24.485256 ]
 [-5.15926   24.485256 ]
 [-5.1592603 24.485256 ]
 [-5.15926   24.485256 ]
 [-5.15926   24.485256 ]
 [-5.1592607 24.485256 ]
 [-5.15926   24.485256 ]
 [-5.160199  24.485054 ]
 [-5.1601973 24.485054 ]
 [-5.15926   24.485256 ]
 [-5.15926   24.485256 ]
 [-5.1592607 24.485256 ]
 [-5.15926   24.485256 ]
 [-5.15926   24.485256 ]
 [-5.15926   24.485256 ]
 [-5.15926   24.485256 ]
 [-5.15926   24.485256 ]
 [-5.15926   24.485256 ]
 [-5.1592603 24.485256 ]
 [-5.1592607 24.485256 ]
 [-5.15926   24.485256 ]
 [-5.15926   24.485256 ]
 [-5.1592593 24.485256 ]
 [-5.15926   24.485256 ]
 [-5.15926   24.485256 ]
 [-5.15926   24.485256 ]
 [-5.1592607 24.485256 ]
 [-5.15926   24.485256 ]
 [-5.159261  24.485256 ]
 [-5.1593094 24.485249 ]
 [-5.15926   24.485256 ]
 [-5.15926   24.485256 ]
 [-5.15926   24.485256 ]
 [-5.1612153 24.484837 ]
 [-5.159261  24.485256 ]
 [-5.1592607 24

 [-9.093767 29.312527]]
25
6357.1147
[[-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [ 6.3355093 10.530773 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  29.825756 ]
 [-9.386678  

2092.654
[[-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.02665  ]
 [-9.8486595 34.

494.20407
[[-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]
 [-8.431652 37.65231 ]]
45
417.07303
[[-8.328278 37.946526]
 [-8.328278 37.946526]
 [-8.32827

1195.683
[[-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [17.849846 -4.233881]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [17.849846 -4.23388 ]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]
 [-8.145933 39.844994]]
54
59.378365
[[-8.188323 40.02762 ]
 [-8.188323 40.02762 ]
 [-8.188323

0.43435454
[[-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]
 [-8.67343  41.102745]]
63
0.5080018
[[-8.721718 41.193424]
 [-8.721718 41.193424]
 [-8.7217

577.868
[[-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [ 8.52178    2.189114 ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [19.588217  -4.8847027]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.66709  ]
 [-8.827806  41.6

11.661407
[[-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]
 [-8.604364 41.7035  ]]
83
11.215645
[[-8.592947 41.690952]
 [-8.592947 41.690952]
 [-8.59294

5.0602207
[[-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]
 [-8.610253 41.518925]]
93
386.76993
[[-8.616148  41.496674 ]
 [-8.616148  41.496674 ]
 [-8.6

345.66663
[[-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [23.197186 -4.735878]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]
 [-8.654675 41.309265]]
103
0.7968219
[[-8.654302 41.291447]
 [-8.654302 41.291447]
 [-8.6543

0.07938437
[[-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 41.1799   ]
 [-8.6210165 4

590.73376
[[-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [24.612465 -4.668573]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [24.612465 -4.668573]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]
 [-8.620872 41.11843 ]]
122
0.335508
[[-8.626904 41.116543]
 [-8.626904 41.116543]
 [-8.62690

130.2575
[[-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.659877  41.1158   ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [-8.661103  41.11908  ]
 [11.167785   2.

248.002
[[-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [25.981792  -4.6014447]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.13591  ]
 [-8.635323  41.1

0.06892675
[[-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]
 [-8.626731 41.152744]]
151
0.19701418
[[-8.625201 41.15425 ]
 [-8.625201 41.15425 ]
 [-8.62

0.0706559
[[-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]
 [-8.63044 41.16398]]
161
0.0446937
[[-8.632291 41.16462 ]
 [-8.632291 41.16462 ]
 [-8.632291 41.16462 ]
 [-8.632291 41.16462 ]
 [-8.632291 41.16462 ]
 [-8.632291 41.16462

0.056860983
[[-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]
 [-8.629096 41.167217]]
171
203.0267
[[-8.629214 41.167107]
 [-8.629214 41.167107]
 [-8.629

189.36874
[[-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [28.170488 -4.477351]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]
 [-8.628372 41.164948]]
180
0.04505331
[[-8.628904 41.164608]
 [-8.628904 41.164608]
 [-8.628

342.17822
[[-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [28.855108  -4.424968 ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [28.855104  -4.4249687]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41.15998  ]
 [-8.629589  41

445.01123
[[-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [29.789814 -4.347557]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [29.789814 -4.347556]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]
 [29.789814 -4.347556]
 [-8.628223 41.1556  ]
 [-8.628223 41.1556  ]]
199
434.14722
[[29.946043 -4.336038]
 [-8.631178 41.155373]
 [-8.6311

120.62472
[[-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [31.014051  -4.2514887]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41.156418 ]
 [-8.622173  41

103.87426
[[-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [31.852953 -4.177914]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]
 [-8.619998 41.15745 ]]
219
0.035889514
[[-8.621219 41.15741 ]
 [-8.621219 41.15741 ]
 [-8.62

1.1346935
[[-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]
 [-8.616311 41.157192]]
229
93.776985
[[-8.615124  41.157272 ]
 [-8.615124  41.157272 ]
 [-8.

0.10323319
[[-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]
 [-8.637632 41.16228 ]]
239
0.09573285
[[-8.639136 41.16294 ]
 [-8.639136 41.16294 ]
 [-8.63

0.033553746
[[-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]
 [-8.620984 41.166256]]
249
0.04890769
[[-8.619431 41.16621 ]
 [-8.619431 41.16621 ]
 [-8.6

In [17]:
#用test.csv做預測後上傳檔案至kaggle
dft = pd.read_csv("test.csv")
dft = dft["POLYLINE"].str.replace("[","")
dft = dft.str.replace("],",",")
dft = dft.str.replace("]","")
dft = dft.str.split(",",-1,True)
dft.fillna(value=0, inplace=True)
dft = dft.astype(float)

In [18]:
dft

0          1         2          3         4          5         6     \
0   -8.585676  41.148522 -8.585712  41.148639 -8.585685  41.148855 -8.585730   
1   -8.610876  41.145570 -8.610858  41.145579 -8.610903  41.145768 -8.610444   
2   -8.585739  41.148558 -8.585730  41.148828 -8.585721  41.148972 -8.586288   
3   -8.613963  41.141169 -8.614125  41.141124 -8.615088  41.140926 -8.615277   
4   -8.619903  41.148036 -8.619894  41.148036  0.000000   0.000000  0.000000   
5   -8.630613  41.178249 -8.630613  41.178249 -8.630739  41.178231 -8.631513   
6   -8.585622  41.148918 -8.585640  41.148900 -8.585919  41.148945 -8.586369   
7   -8.582922  41.181057 -8.582004  41.181813 -8.581077  41.182965 -8.580114   
8   -8.606529  41.144670 -8.606673  41.144724 -8.606799  41.144706 -8.606790   
9   -8.585658  41.148576 -8.585703  41.148603 -8.585730  41.148603 -8.585739   
10  -8.591229  41.162706 -8.591229  41.162715 -8.591220  41.162715 -8.591004   
11  -8.585694  41.148603 -8.585757  41.148684 -8.585712  41.148882 -8.585757   
12  -8.580105  41.159394 -8.580231  41.159358 -8.581518  41.159349 -8.582517   
13  -8.665353  41.186160 -8.666892  41.188311 -8.667045  41.190705 -8.665812   
14  -8.649423  41.154354 -8.650197  41.154138 -8.650323  41.153832 -8.649045   
15  -8.618373  41.136003 -8.618382  41.135877 -8.618445  41.135022 -8.618445   
16  -8.627094  41.166936 -8.627049  41.166900 -8.626644  41.166900 -8.626626   
17  -8.607861  41.146236 -8.607915  41.146236 -8.607924  41.146236 -8.607924   
18  -8.585667  41.148567 -8.585694  41.148639 -8.585712  41.148747 -8.585775   
19  -8.667414  41.161671 -8.667423  41.161662 -8.667414  41.161671 -8.667405   
20  -8.585712  41.148540 -8.585703  41.148549 -8.585712  41.148558 -8.585721   
21  -8.612757  41.137722 -8.612658  41.137785 -8.612631  41.137812 -8.612460   
22  -8.625816  41.151294 -8.625942  41.151330 -8.626113  41.151294 -8.626284   
23  -8.585658  41.148486 -8.585658  41.148486 -8.585658  41.148486 -8.585658   
24  -8.630667  41.154867 -8.630928  41.154660 -8.632386  41.153166 -8.633241   
25  -8.602830  41.179644 -8.603163  41.179716 -8.604648  41.180139 -8.604990   
26  -8.592120  41.160735 -8.591499  41.161689 -8.592093  41.161581 -8.593029   
27  -8.585685  41.148900 -8.586018  41.148990 -8.587017  41.149098  0.000000   
28  -8.628777  41.160978 -8.628741  41.160969 -8.628750  41.160960 -8.628777   
29  -8.585730  41.148513 -8.585748  41.148846 -8.586198  41.149044 -8.586234   
..        ...        ...       ...        ...       ...        ...       ...   
290 -8.627697  41.175432 -8.627463  41.174766 -8.626617  41.173038 -8.625924   
291 -8.661942  41.183703 -8.661942  41.183694 -8.661933  41.183649 -8.663220   
292 -8.573454  41.147199 -8.573499  41.147262 -8.573517  41.147289 -8.573526   
293 -8.606403  41.144454 -8.606430  41.144544 -8.606430  41.144562 -8.606430   
294 -8.610264  41.140845 -8.610066  41.140809 -8.610057  41.140845 -8.610048   
295 -8.612136  41.172849 -8.612667  41.172804 -8.612685  41.172084  0.000000   
296 -8.641251  41.165658 -8.641260  41.165712 -8.641269  41.165721 -8.641863   
297 -8.613891  41.141286 -8.614350  41.141115 -8.615511  41.140701 -8.616780   
298 -8.620461  41.156514 -8.620506  41.156469 -8.620641  41.156460 -8.620650   
299 -8.617581  41.146110 -8.617590  41.146092 -8.617518  41.145678 -8.617212   
300 -8.588457  41.148558 -8.588844  41.147199 -8.587206  41.147298 -8.585613   
301 -8.589096  41.155506 -8.589105  41.155515 -8.589114  41.155515 -8.589123   
302 -8.668575  41.157891 -8.668575  41.157909 -8.667999  41.158161 -8.666046   
303 -8.607456  41.148720 -8.607060  41.148621 -8.606772  41.148513 -8.606475   
304 -8.617113  41.160042 -8.617122  41.160069 -8.617122  41.160114 -8.616726   
305 -8.628984  41.165874 -8.629074  41.165874 -8.630334  41.165343 -8.631657   
306 -8.619723  41.161905 -8.619768  41.161959 -8.619813  41.161995 -8.619822   
307 -8.623566  41.144310 -8.623593  41.144328 -8.624790  41.144706 -8.627292   
308 -8.61

In [19]:
dfnew = pd.DataFrame(np.zeros((len(dft),(len(x_data.iloc[0]) - len(dft.iloc[0]))))) 
dft = pd.concat([dft, dfnew],axis = 1)

In [20]:
output = sess.run(outputlayer, feed_dict = {xs : dft})

In [21]:
#output.csv需要打開更改row跟col的名稱才能上傳kaggle
output  = pd.DataFrame(output)
output.to_csv("outputmidtest2.csv")